export const informaciones: Record<string, string> = {
  media: 'La media aritmética es una de las medidas de tendencia central más utilizadas en estadística. Se calcula sumando todos los valores de un conjunto de datos y dividiendo el resultado entre el número total de elementos. Su principal utilidad es ofrecer un valor representativo del conjunto de datos, facilitando la comparación entre diferentes grupos. Sin embargo, es sensible a valores extremos (outliers), lo que puede afectar su interpretación. Por ejemplo, en un grupo de salarios donde la mayoría gana entre 1,000 y 2,000 dólares, pero un individuo gana 50,000, la media puede dar una percepción distorsionada del salario típico.',

  mediana: 'La mediana es otra medida de tendencia central que representa el valor central de un conjunto de datos ordenado. Si el número de elementos es impar, la mediana es el valor que ocupa la posición central. Si es par, se obtiene promediando los dos valores centrales. A diferencia de la media, la mediana no se ve afectada por valores extremadamente altos o bajos, por lo que es una mejor opción cuando los datos tienen una distribución asimétrica. Un ejemplo de su uso es en los ingresos de una población: si la distribución es muy desigual, la mediana puede reflejar mejor el ingreso típico que la media.',

  moda: 'La moda es el valor que aparece con mayor frecuencia en un conjunto de datos. Puede haber una única moda (unimodal), más de una moda (multimodal) o ninguna moda si todos los valores ocurren con la misma frecuencia. Se utiliza en análisis de datos para identificar tendencias y patrones. Un ejemplo práctico es en encuestas donde se analiza la respuesta más común a una pregunta de opción múltiple, lo que permite conocer las preferencias de una población.',

  varianza: 'La varianza es una medida de dispersión que indica cuánto se alejan los valores de un conjunto de datos respecto a la media. Se calcula promediando el cuadrado de las diferencias entre cada valor y la media. Una varianza alta indica que los datos están muy dispersos, mientras que una varianza baja sugiere que los valores están más concentrados cerca de la media. Se usa en estadísticas para medir la volatilidad de datos financieros, como las acciones en la bolsa, donde una varianza alta indica mayor riesgo.',

  desviacionEstandar: 'La desviación estándar es la raíz cuadrada de la varianza y representa la dispersión promedio de los datos respecto a la media. Es una medida más intuitiva de la variabilidad porque mantiene las mismas unidades que los datos originales. Una desviación estándar alta indica que los valores están muy dispersos, mientras que una baja sugiere que están agrupados cerca de la media. Se usa en múltiples disciplinas, como control de calidad, donde ayuda a determinar si un proceso de producción es consistente.',

  covarianza: 'La covarianza mide el grado en que dos variables cambian juntas. Si ambas variables tienden a aumentar o disminuir simultáneamente, la covarianza será positiva; si una aumenta mientras la otra disminuye, será negativa. Sin embargo, la magnitud de la covarianza no es fácil de interpretar por sí sola, ya que depende de las unidades de las variables. Un ejemplo de uso es en economía, donde se analiza la relación entre la oferta y la demanda de un producto.',

  correlacion: 'La correlación cuantifica la relación entre dos variables en una escala estandarizada de -1 a 1. Un valor cercano a 1 indica una fuerte relación positiva (cuando una variable aumenta, la otra también lo hace), un valor cercano a -1 indica una fuerte relación negativa (cuando una aumenta, la otra disminuye), y un valor cercano a 0 sugiere que no hay relación lineal. Se utiliza en diversas áreas como la psicología, donde se analiza la relación entre hábitos de estudio y desempeño académico.',

  coeficienteCorrelacion: 'El coeficiente de correlación de Pearson es una medida específica de la correlación entre dos variables cuantitativas. Se calcula dividiendo la covarianza entre el producto de las desviaciones estándar de ambas variables. Su valor varía entre -1 y 1, lo que permite interpretar la fuerza y dirección de la relación. Se usa comúnmente en estudios científicos para evaluar relaciones entre factores, como la correlación entre ejercicio físico y salud cardiovascular.',

  permutaciones: 'Las permutaciones representan el número de maneras en que se pueden ordenar r elementos seleccionados de un conjunto de n elementos. En este caso, el orden sí importa. Se calcula con la fórmula P(n, r) = n! / (n - r)!. Se utiliza en escenarios donde el orden es crucial, como la organización de asientos en un evento o la creación de combinaciones de contraseñas.',

  combinaciones: 'Las combinaciones representan el número de maneras en que se pueden seleccionar r elementos de un conjunto de n elementos sin importar el orden. La fórmula es C(n, r) = n! / [r!(n - r)!]. Se aplica en contextos como la selección de equipos deportivos o la elección de un grupo de estudiantes para un proyecto.'

};
